imports:
    - { resource: resources/ }

parameters:
    cached_data_path: '%env(string:CACHED_DATA_PATH)%'
    report_path: '%env(string:REPORT_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    monolog.formatter.pretty:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"
            - "Y-m-d H:i:s"
            - true
            - true

    App\Service\Simla\ApiWrapperFactory:
        class: 'App\Service\Simla\ApiWrapperFactory'
        arguments:
            $httpClient: '@http_client_simla.guzzle'
